export default [
  {
    id: "horizontal-1",
    sourcePosition: "right",
    type: "input",
    data: { label: "Input" },
    position: { x: 0, y: 200 },
  },
  {
    id: "horizontal-2",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Research" },
    position: { x: 250, y: 0 },
  },
  {
    id: "horizontal-3",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Planning" },
    position: { x: 250, y: 160 },
  },
  {
    id: "horizontal-4",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Designing" },
    position: { x: 250, y: 320 },
  },
  {
    id: "horizontal-5",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Manufacturing" },
    position: { x: 250, y: 480 },
  },
  {
    id: "horizontal-6",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Sales/Marketing" },
    position: { x: 250, y: 640 },
  },
  {
    id: "horizontal-7",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Node 7" },
    position: { x: 750, y: 0 },
  },
  {
    id: "horizontal-9",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "External" },
    position: { x: 500, y: -40 },
  },
  {
    id: "horizontal-10",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Internal" },
    position: { x: 500, y: 40 },
  },
  {
    id: "horizontal-11",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "External" },
    position: { x: 500, y: 120 },
  },
  {
    id: "horizontal-12",
    sourcePosition: "right",
    targetPosition: "left",
    data: { label: "Internal" },
    position: { x: 500, y: 200 },
  },
];
